name: Semantic-Release
on:
  workflow_dispatch:

env:
  NODE_VERSION: ${{ '20' }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Set release tag
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      initial-version: ${{ steps.save-initial-version.outputs.version }}
      version: ${{ steps.save-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install Node.js dependencies
        run: | 
          yarn install --frozen-lockfile --immutable --non-interactive --prefer-offline

      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GH_TOKEN: ${{ github.token }}
          GITHUB_URL: ${{ github.server_url }}
          HUSKY: 0
        run: yarn semantic-release
